package myUtil.rule;/*
 * This file was automatically generated by EvoSuite
 * Sun Jul 08 02:38:00 GMT 2018
 */


import org.junit.Test;

import static org.junit.Assert.*;

public class Variable_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Variable variable0 = new Variable("");
      String string0 = variable0.getIdentifier();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Variable variable0 = new Variable(">.i< Fq5OsMQ");
      boolean boolean0 = variable0.equals(variable0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Variable variable0 = new Variable(">.i< Fq5OsMQ");
      boolean boolean0 = variable0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Variable variable0 = new Variable(">.i< Fq5OsMQ");
      boolean boolean0 = variable0.equals(">.i< Fq5OsMQ");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Variable variable0 = null;
      try {
        variable0 = new Variable((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Identifier cannot be null
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Variable variable0 = new Variable(">.i< Fq5OsMQ");
      variable0.hashCode();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Variable variable0 = new Variable(">.i< Fq5OsMQ");
      String string0 = variable0.getIdentifier();
      assertEquals(">.i< Fq5OsMQ", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Variable variable0 = new Variable(">.i< Fq5OsMQ");
      String string0 = variable0.toString();
      assertEquals("VAR:>.i< Fq5OsMQ", string0);
  }
}
